/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import arbolbinario.NodoArbol;
import arbolbinario.Ope_adiconales;
import arbolbinario.Recorridos_Arbol;
import arbolbinario.TADArbol;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.awt.Rectangle;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author duvanbotello
 */
public class GUI extends javax.swing.JFrame {

    private final JFrame dibujoEmergente = new JFrame("Representación gráfica");
    private final TADArbol arbol1 = new TADArbol();
    private int numNodos = 0;
    private Ope_adiconales operacion_arbol = new Ope_adiconales();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.dibujoEmergente.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    private void cargas() {
        arbol1.setCant(0);
        arbol1.setCanth(0);
        txt_cNodos.setText(arbol1.cantidadNodos(arbol1.getRaiz()));
        txt_hojas.setText(arbol1.cantidadHOjas(arbol1.getRaiz()));
        txt_mayor.setText(operacion_arbol.mayorValor(arbol1.getRaiz()));
        txt_valormenor.setText(operacion_arbol.menorValor(arbol1.getRaiz()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        txt_hojas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cNodos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_valormenor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_mayor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btm_insertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_operaciones = new javax.swing.JComboBox<>();
        btm_buscar = new javax.swing.JButton();
        btm_borrar = new javax.swing.JButton();
        btm_podar = new javax.swing.JButton();
        btm_borrarmenor = new javax.swing.JButton();
        btm_borrarmayor = new javax.swing.JButton();
        btm_bpadre = new javax.swing.JButton();
        btm_bhijos = new javax.swing.JButton();
        cmb2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        lb_respuestas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARBOLES BINARIOS DE BUSQUEDAD");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Representacion Grafica del Arbol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14), new java.awt.Color(27, 31, 157))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jInternalFrame2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setEnabled(false);
        jInternalFrame2.setFocusCycleRoot(false);
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jInternalFrame2);
        jInternalFrame2.setBounds(0, 0, 510, 290);

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 290));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        jLabel2.setText("Cantidad De Nodos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        txt_hojas.setEditable(false);
        txt_hojas.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txt_hojas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_hojas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_hojas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hojas2.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 40, 30));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        jLabel5.setText("Cantidad De Hojas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        txt_cNodos.setEditable(false);
        txt_cNodos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txt_cNodos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cNodos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_cNodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nodos.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 40, 30));

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        jLabel7.setText("Valor Menor");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        txt_valormenor.setEditable(false);
        txt_valormenor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txt_valormenor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_valormenor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_valormenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 90, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menor.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 40, 30));

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        jLabel9.setText("Valor mayor");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        txt_mayor.setEditable(false);
        txt_mayor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txt_mayor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mayor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 90, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mayor.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operaciones De Arboles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14), new java.awt.Color(27, 31, 157))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(39, 39, 118));

        btm_insertar.setBackground(new java.awt.Color(81, 201, 130));
        btm_insertar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insertar.png"))); // NOI18N
        btm_insertar.setText("Insertar ");
        btm_insertar.setBorder(null);
        btm_insertar.setEnabled(false);
        btm_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_insertarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Tipo de Operaciones:");

        cmb_operaciones.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmb_operaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Recursivas", "Iterativas" }));
        cmb_operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_operacionesActionPerformed(evt);
            }
        });

        btm_buscar.setBackground(new java.awt.Color(180, 159, 53));
        btm_buscar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btm_buscar.setText("Buscar");
        btm_buscar.setBorder(null);
        btm_buscar.setEnabled(false);
        btm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_buscarActionPerformed(evt);
            }
        });

        btm_borrar.setBackground(new java.awt.Color(227, 32, 73));
        btm_borrar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        btm_borrar.setText("Borrar");
        btm_borrar.setBorder(null);
        btm_borrar.setEnabled(false);
        btm_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_borrarActionPerformed(evt);
            }
        });

        btm_podar.setBackground(new java.awt.Color(91, 195, 94));
        btm_podar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_podar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/podar.png"))); // NOI18N
        btm_podar.setText("Podar");
        btm_podar.setBorder(null);
        btm_podar.setEnabled(false);
        btm_podar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_podarActionPerformed(evt);
            }
        });

        btm_borrarmenor.setBackground(java.awt.Color.lightGray);
        btm_borrarmenor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_borrarmenor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menor.png"))); // NOI18N
        btm_borrarmenor.setText("Borrar Menor");
        btm_borrarmenor.setBorder(null);
        btm_borrarmenor.setEnabled(false);
        btm_borrarmenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_borrarmenorActionPerformed(evt);
            }
        });

        btm_borrarmayor.setBackground(java.awt.Color.lightGray);
        btm_borrarmayor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_borrarmayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mayor.png"))); // NOI18N
        btm_borrarmayor.setText("Borrar Mayor");
        btm_borrarmayor.setBorder(null);
        btm_borrarmayor.setEnabled(false);
        btm_borrarmayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_borrarmayorActionPerformed(evt);
            }
        });

        btm_bpadre.setBackground(new java.awt.Color(222, 222, 52));
        btm_bpadre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_bpadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btm_bpadre.setText("Buscar Padre");
        btm_bpadre.setBorder(null);
        btm_bpadre.setEnabled(false);
        btm_bpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_bpadreActionPerformed(evt);
            }
        });

        btm_bhijos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btm_bhijos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btm_bhijos.setText("Buscar Hijos");
        btm_bhijos.setBorder(null);
        btm_bhijos.setEnabled(false);
        btm_bhijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_bhijosActionPerformed(evt);
            }
        });

        cmb2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Pre-Orden", "In-Orden", "Post-Orden" }));
        cmb2.setEnabled(false);
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Recorridos:");

        lb_respuestas.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lb_respuestas.setForeground(new java.awt.Color(254, 95, 95));
        lb_respuestas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btm_insertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btm_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btm_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btm_podar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btm_borrarmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btm_borrarmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btm_bpadre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btm_bhijos)
                        .addGap(31, 31, 31)
                        .addComponent(lb_respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmb_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_podar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_borrarmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_borrarmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_respuestas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btm_bpadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btm_bhijos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setForeground(java.awt.Color.black);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/definiciones.png"))); // NOI18N
        jMenu1.setText("Definiciones");
        jMenu1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arbol.png"))); // NOI18N
        jMenuItem1.setText("¿Que es un Arbol?");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arbolnesbinarios.png"))); // NOI18N
        jMenuItem2.setText("Arboles Binarios");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recorrido.png"))); // NOI18N
        jMenuItem3.setText("Tipos de Recorridos");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/metodos.png"))); // NOI18N
        jMenu2.setText("Metodos");
        jMenu2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jMenu2.add(jSeparator3);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iterativo.png"))); // NOI18N
        jMenu3.setText("Iterativos");
        jMenu2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recursivo.png"))); // NOI18N
        jMenu4.setText("Recursivos");
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_insertarActionPerformed
        switch (cmb_operaciones.getSelectedIndex()) {
            case 1:
                try {
                    int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero para insertar:"));
                    if (this.arbol1.agregarRecursivo(dato)) {
                        JOptionPane.showMessageDialog(null, "El dato fue insertado correctamente", " ...", 1);
                        repintarArbol();
                        cargas();
                        inicializar();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);

                }
                break;
            case 2:
                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor Seleccione Un tipo de Operacion", "Seleccione...", 0);
                break;
        }

    }//GEN-LAST:event_btm_insertarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Carbol v = new Carbol();
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_buscarActionPerformed
        switch (cmb_operaciones.getSelectedIndex()) {
            case 1:
                try {
                    int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero para buscar:"));
                    if (true == arbol1.buscar(arbol1.getRaiz(), dato)) {
                        lb_respuestas.setText("El dato " + dato + " existe dentro del arbol");
                    } else {
                        lb_respuestas.setText("El dato No existe");
                    }
                } catch (HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "No se pudo buscar ningun dato", "Intenta de nuevo...", 0);

                }
                break;
            case 2:
                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor Seleccione Un tipo de Operacion", "Seleccione...", 0);
                break;
        }
    }//GEN-LAST:event_btm_buscarActionPerformed

    private void btm_podarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_podarActionPerformed
        switch (cmb_operaciones.getSelectedIndex()) {
            case 1:
                arbol1.PodarHOjas(arbol1.getRaiz());
                repintarArbol();
                cargas();
                lb_respuestas.setText("Arbol Podado con EXITO....");
                break;
            case 2:
                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor Seleccione Un tipo de Operacion", "Seleccione...", 0);
                break;
        }
    }//GEN-LAST:event_btm_podarActionPerformed

    private void btm_bhijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_bhijosActionPerformed
        switch (cmb_operaciones.getSelectedIndex()) {
            case 1:
                try {
                    int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero para saber hijos:"));
                    arbol1.saberHIjos(arbol1.getRaiz(), dato);
                } catch (HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "No se pudo buscar ningun dato", "Intenta de nuevo...", 0);
                }

                break;
            case 2:
                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor Seleccione Un tipo de Operacion", "Seleccione...", 0);
                break;
        }
    }//GEN-LAST:event_btm_bhijosActionPerformed

    private void btm_bpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_bpadreActionPerformed
        switch (cmb_operaciones.getSelectedIndex()) {
            case 1:
                try {
                    int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero Hijo para saber Padre:"));

                    try {
                        NodoArbol padre = null;
                        String padreStr = arbol1.saberPadre(arbol1.getRaiz(), dato, padre);
                        if (padreStr.equals("El Nodo raiz no contiene padre")) {
                            lb_respuestas.setText(padreStr);
//                            JOptionPane.showMessageDialog(null, padreStr);
                        } else {
                            lb_respuestas.setText("EL nodo padre es: " + padreStr);
//                            JOptionPane.showMessageDialog(null, "EL nodo padre es: " + padreStr);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error dato no existe");
                    }

                } catch (HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "No se pudo buscar ningun dato", "Intenta de nuevo...", 0);
                }

                break;
            case 2:
                break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor Seleccione Un tipo de Operacion", "Seleccione...", 0);
                break;
        }
    }//GEN-LAST:event_btm_bpadreActionPerformed
    private void inicializar() {
        btm_bpadre.setEnabled(true);
        btm_buscar.setEnabled(true);
        btm_bhijos.setEnabled(true);
        btm_podar.setEnabled(true);
        btm_borrarmayor.setEnabled(true);
        btm_borrarmenor.setEnabled(true);
        btm_borrar.setEnabled(true);

    }

    private void desactivar() {
        btm_bpadre.setEnabled(false);
        btm_buscar.setEnabled(false);
        btm_bhijos.setEnabled(false);
        btm_podar.setEnabled(false);
        btm_borrarmayor.setEnabled(false);
        btm_borrarmenor.setEnabled(false);
        btm_borrar.setEnabled(false);

    }
    private void cmb_operacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_operacionesActionPerformed
        switch (cmb_operaciones.getSelectedIndex()) {
            case 1:
                btm_insertar.setEnabled(true);
                cmb2.setEnabled(true);
                break;
            case 2:
                btm_insertar.setEnabled(true);
                cmb2.setEnabled(true);
                break;
            case 0:
                btm_insertar.setEnabled(false);
                cmb2.setEnabled(false);
                desactivar();
                break;
        }
    }//GEN-LAST:event_cmb_operacionesActionPerformed
    private String ImprimirOrde(LinkedList x) {
        String orden = "";
        for (Object c : x) {
            orden = orden + c.toString() + "\n";
        }
        return orden;
    }
    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed
        if (arbol1.getRaiz() != null) {
            Recorridos_Arbol recorrer = new Recorridos_Arbol();
            LinkedList<Integer> orden = new LinkedList();
            switch (cmb2.getSelectedIndex()) {
                case 1:
                    recorrer.Pre_Orden(arbol1.getRaiz(), orden);
                    lb_respuestas.setText("Recorrido de izquierda a derecha");
                    JOptionPane.showMessageDialog(null, "Recorrido Pre_orden \n" + ImprimirOrde(orden));
                    cmb2.setSelectedIndex(0);
                    break;
                case 2:
                    recorrer.In_orden(arbol1.getRaiz(), orden);
                    lb_respuestas.setText("Recorrido de izquierda, raiz, derecha.");
                    JOptionPane.showMessageDialog(null, "Recorrido In_orden \n" + ImprimirOrde(orden));
                    cmb2.setSelectedIndex(0);
                    break;
                case 3:
                    recorrer.Post_orden(arbol1.getRaiz(), orden);
                    lb_respuestas.setText("Recorrido de izquierda, derecha, raiz.");
                    JOptionPane.showMessageDialog(null, "Recorrido Post_orden \n" + ImprimirOrde(orden));
                    cmb2.setSelectedIndex(0);
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Arbol Vacio");
        }


    }//GEN-LAST:event_cmb2ActionPerformed

    private void btm_borrarmenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_borrarmenorActionPerformed
        try {
            arbol1.borrarMenor();
            repintarArbol();
            cargas();
        } catch (Exception e) {
            repintarArbol();
            cargas();
        }
    }//GEN-LAST:event_btm_borrarmenorActionPerformed

    private void btm_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_borrarActionPerformed
        try {
            int dato = Integer.parseInt(JOptionPane.showInputDialog("Digite dato entero para borrar: "));
            arbol1.borrar(dato);

            repintarArbol();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btm_borrarActionPerformed

    private void btm_borrarmayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_borrarmayorActionPerformed
        try {
            arbol1.borrarMayor();
            repintarArbol();
            cargas();
        } catch (Exception e) {
            repintarArbol();
            cargas();
        }
    }//GEN-LAST:event_btm_borrarmayorActionPerformed
    private void repintarArbol() {
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
        this.jInternalFrame2.add(this.arbol1.getdibujo(arbol1), BorderLayout.CENTER);
        this.dibujoEmergente.getContentPane().add(this.arbol1.getdibujo(arbol1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_bhijos;
    private javax.swing.JButton btm_borrar;
    private javax.swing.JButton btm_borrarmayor;
    private javax.swing.JButton btm_borrarmenor;
    private javax.swing.JButton btm_bpadre;
    private javax.swing.JButton btm_buscar;
    private javax.swing.JButton btm_insertar;
    private javax.swing.JButton btm_podar;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JComboBox<String> cmb_operaciones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lb_respuestas;
    private javax.swing.JTextField txt_cNodos;
    private javax.swing.JTextField txt_hojas;
    private javax.swing.JTextField txt_mayor;
    private javax.swing.JTextField txt_valormenor;
    // End of variables declaration//GEN-END:variables
}
